#!/usr/bin/env python3
"""generate-build-info — capture git provenance into src/dharmatiles/_build_info.py.

Run once before packaging or distributing.  The generated file is a build
artifact: do not commit it to source control.

Usage:
    generate-build-info          # writes to the package directory
    python src/scripts/generate_build_info.py

The file it writes is imported at runtime by dharmatiles.build_info.get_build_info().
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_OUT = Path(__file__).parent.parent / "dharmatiles" / "_build_info.py"


def _git(*args: str) -> str:
    try:
        r = subprocess.run(["git", *args], capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else ""
    except FileNotFoundError:
        return ""


def capture() -> dict:
    now          = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    commit       = _git("rev-parse", "HEAD")            or "unknown"
    commit_short = _git("rev-parse", "--short", "HEAD") or "unknown"
    branch       = _git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    is_dirty     = bool(_git("status", "--porcelain"))
    describe     = _git("describe", "--tags", "--long", "--always")

    tag = ""
    commits_since = 0
    version = "unknown"

    if describe:
        m = re.match(r'^(.+)-(\d+)-g([0-9a-f]+)$', describe)
        if m:
            tag           = m.group(1)
            commits_since = int(m.group(2))
            short         = m.group(3)
            if commits_since == 0:
                version = tag + ("-dirty" if is_dirty else "")
            else:
                version = f"{tag}-{commits_since}-g{short}" + ("-dirty" if is_dirty else "")
        else:
            short   = describe
            version = f"g{short}" + ("-dirty" if is_dirty else "")

    # Collect recent commits since tag (for release notes / diagnostics)
    log_range = f"{tag}..HEAD" if tag else "HEAD"
    log_out   = _git("log", "--oneline", log_range)
    commits   = [line.strip() for line in log_out.splitlines() if line.strip()]

    return dict(
        version=version,
        commit=commit,
        commit_short=commit_short,
        branch=branch,
        tag=tag,
        commits_since_tag=commits_since,
        build_timestamp=now,
        is_dirty=is_dirty,
        commits=commits,
    )


def write(data: dict, path: Path) -> None:
    lines = [
        "# AUTO-GENERATED by generate-build-info — do not edit or commit.",
        f"# Generated: {data['build_timestamp']}",
        "DATA = {",
    ]
    for k, v in data.items():
        lines.append(f"    {k!r}: {v!r},")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    data = capture()
    write(data, _OUT)
    print(f"wrote {_OUT}")
    print(f"  version          : {data['version']}")
    print(f"  commit           : {data['commit_short']} ({data['commit'][:16]}…)")
    print(f"  branch           : {data['branch']}")
    print(f"  tag              : {data['tag'] or '(none)'}")
    print(f"  commits_since_tag: {data['commits_since_tag']}")
    print(f"  build_timestamp  : {data['build_timestamp']}")
    print(f"  is_dirty         : {data['is_dirty']}")
    print(f"  commits          : {len(data['commits'])} entries")


if __name__ == "__main__":
    main()
